name: glossary_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  webview_flutter: ^2.0.14
  flutter_native_splash: ^2.2.16

dev_dependencies:
  flutter_launcher_icons: ^0.11.0

flutter_icons:
  android: "launcher_icon"
  image_path: "assets/logo.png"

  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_native_splash:
  color: "ffffff"
  image: assets/logoGlossary.png

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/logoGlossary.png
