name: glossary_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  webview_flutter: ^2.0.14
  flutter_native_splash: ^2.2.16
  dio: ^4.0.6
  flutter_bloc: ^8.1.1
  smooth_page_indicator: ^1.0.0+2
  shared_preferences: ^2.0.15
  passwordfield: ^0.1.0
  firebase_core: ^2.4.0
  firebase_auth: ^4.2.1
  google_sign_in: ^5.4.2
  persistent_bottom_nav_bar: ^5.0.2

dev_dependencies:
  flutter_launcher_icons: ^0.11.0

flutter_icons:
  android: "launcher_icon"
  image_path: "assets/logo.png"

  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_native_splash:
  color: "ffffff"
  image: assets/logoGlossary.png

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/logoGlossary.png
    - assets/Glossary-of-Banking-Terms-RVR-1.jpg
    - assets/addGlossary.png
    - assets/introImages/intro1.png
    - assets/introImages/intro11.png
    - assets/introImages/intro22.png
    - assets/introImages/intro33.png
    - assets/auth/signIn.webp
    - assets/auth/signUp.webp
    - assets/auth/fakeUser.png
