// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANm0kSWivsmtjOPnjRp2MaV60qRIvkGz4',
    appId: '1:581597019708:web:d1a08b62943da95d290d39',
    messagingSenderId: '581597019708',
    projectId: 'glossary-b8ca4',
    authDomain: 'glossary-b8ca4.firebaseapp.com',
    storageBucket: 'glossary-b8ca4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjzaUGAjea7gKgPEeTb9mkxBPDdOZWFyY',
    appId: '1:581597019708:android:7d7405bf91eb25e6290d39',
    messagingSenderId: '581597019708',
    projectId: 'glossary-b8ca4',
    storageBucket: 'glossary-b8ca4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBihQD91825rVOb_oSWvK6jQktaq55nNIs',
    appId: '1:581597019708:ios:7882b6676affd1c1290d39',
    messagingSenderId: '581597019708',
    projectId: 'glossary-b8ca4',
    storageBucket: 'glossary-b8ca4.appspot.com',
    iosClientId:
        '581597019708-p9a5e04p4mrlj84dtnqt092ccnfdr3k8.apps.googleusercontent.com',
    iosBundleId: 'com.example.glossaryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBihQD91825rVOb_oSWvK6jQktaq55nNIs',
    appId: '1:581597019708:ios:7882b6676affd1c1290d39',
    messagingSenderId: '581597019708',
    projectId: 'glossary-b8ca4',
    storageBucket: 'glossary-b8ca4.appspot.com',
    iosClientId:
        '581597019708-p9a5e04p4mrlj84dtnqt092ccnfdr3k8.apps.googleusercontent.com',
    iosBundleId: 'com.example.glossaryApp',
  );
}
